"""Configuration, in one place.

Paths come from the environment with defaults that work inside WSL. The
warehouse deliberately does NOT live under /mnt/d (the Windows mount): Delta
Lake commits by writing a JSON file into _delta_log and renaming it, which
needs atomic rename plus consistent directory listing, and DrvFs does not
reliably provide either. The code stays on /mnt/d so git works from Windows.
"""

import os
import pathlib

# WSL-native ext4 by default. Override with LAKEHOUSE_ROOT to move it.
LAKEHOUSE_ROOT = pathlib.Path(
    os.environ.get("LAKEHOUSE_ROOT", "/root/lakehouse")
).expanduser()

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[2]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
LOGS_DIR = PROJECT_ROOT / "logs"

RATINGS_CSV = RAW_DIR / "ratings.csv"
MOVIES_CSV = RAW_DIR / "movies.csv"

# Corrections that arrived after the initial load. Generated by
# scripts/make_corrections.py, not downloaded: an upsert demo needs controlled
# late-arriving data, and real data will not hand you that on demand.
CORRECTIONS_CSV = RAW_DIR / "rating_corrections.csv"

# --- Spark sizing -----------------------------------------------------------
# Sized for a laptop, not a cluster. 1 GB driver heap is enough for 100k rows
# and keeps the whole pipeline runnable alongside an editor.
DRIVER_MEMORY = os.environ.get("SPARK_DRIVER_MEMORY", "1g")
MASTER = os.environ.get("SPARK_MASTER", "local[2]")
SHUFFLE_PARTITIONS = os.environ.get("SPARK_SHUFFLE_PARTITIONS", "4")

# --- Table names ------------------------------------------------------------
BRONZE_RATINGS = "bronze_ratings"
BRONZE_MOVIES = "bronze_movies"
SILVER_RATINGS = "silver_ratings"
SILVER_MOVIES = "silver_movies"
QUARANTINE_RATINGS = "quarantine_ratings"
GOLD_FACT_RATINGS = "fct_rating"
GOLD_DIM_MOVIE = "dim_movie"
GOLD_DIM_USER = "dim_user"
GOLD_AGG_MONTHLY = "agg_monthly_movie_ratings"
DQ_RESULTS = "dq_results"

# Valid MovieLens ratings are 0.5 to 5.0 in 0.5 steps. Values outside that are
# corrupt rather than merely unusual, so they fail the gate.
RATING_MIN = 0.5
RATING_MAX = 5.0


def table_path(table: str) -> str:
    """Absolute path for a Delta table under the warehouse root."""
    return str(LAKEHOUSE_ROOT / "tables" / table)


def ensure_dirs() -> None:
    (LAKEHOUSE_ROOT / "tables").mkdir(parents=True, exist_ok=True)
    (LAKEHOUSE_ROOT / "spark_warehouse").mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
